language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - pandoc

# Setup anaconda
# This is just a simple way to acquire the necessary libraries for numpy/scipy/matplotlib to be installed correctly.
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda info -a

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip atlas numpy scipy matplotlib
  - pip install nose nosexcover nose-exclude pypandoc python-coveralls zest.releaser[recommended]

script:
  # Run tests
  - nosetests --with-xcoverage --logging-level=DEBUG --cover-package=timetools --cover-tests
  # Test building the distribution package
  - python3 setup.py bdist_wheel

# Calculate coverage
after_success:
  - coveralls
  
sudo: false
